# Generated by Django 2.0.1 on 2018-01-19 15:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ircimages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('irclog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(null=True)),
                ('caption', models.CharField(max_length=20, null=True, verbose_name='Caption')),
                ('extension', models.CharField(max_length=10, null=True, verbose_name='Extension')),
                ('image', models.ImageField(upload_to=ircimages.models.upload_path_handler)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='ircimages.ImageSet'),
        ),
        migrations.AddField(
            model_name='image',
            name='related_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='irclog.Log'),
        ),
    ]
