# Generated by Django 2.2.1 on 2019-05-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ircimages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(max_length=2000, null=True, verbose_name='Caption'),
        ),
    ]
