# Generated by Django 2.0.1 on 2018-02-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ircimages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumb',
            field=models.ImageField(default=None, upload_to='thumb/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
