# Generated by Django 2.2.1 on 2019-05-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ircimages', '0002_auto_20190525_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(max_length=1000, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='original_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
