# Generated by Django 2.0.1 on 2018-06-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ircimages', '0004_auto_20180302_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(max_length=1000, null=True, verbose_name='Caption'),
        ),
    ]
