# Generated by Django 2.2.1 on 2019-05-25 00:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='channel name')),
                ('topic', models.TextField(null=True, verbose_name='channel topic')),
                ('ircusers', models.CharField(max_length=100, null=True, verbose_name='channel user')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('PRIVMSG', 'priv'), ('NOTICE', 'notice')], default='PRIVMSG', max_length=10, verbose_name='irc command')),
                ('nick', models.CharField(default='test', max_length=20, verbose_name='irc nick')),
                ('message', models.CharField(max_length=200, verbose_name='irc message')),
                ('attached_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='attached image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('is_irc', models.BooleanField(default=True)),
                ('is_from_log', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='irclog.Channel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
