# Generated by Django 2.2.1 on 2019-05-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irclog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.CharField(max_length=500, verbose_name='irc message'),
        ),
    ]
