# Generated by Django 2.0.1 on 2018-06-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irclog', '0003_log_is_irc'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_from_log',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
