# Generated by Django 2.0.1 on 2018-06-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irclog', '0004_log_is_from_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='is_from_log',
            field=models.BooleanField(default=True),
        ),
    ]
