# Generated by Django 2.0.1 on 2018-06-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irclog', '0005_auto_20180610_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='is_from_log',
            field=models.BooleanField(default=False),
        ),
    ]
